Ajout de message d'erreur

diff --git a/.github/workflows/run-test.yml b/.github/workflows/run-test.yml
--- a/.github/workflows/run-test.yml
+++ b/.github/workflows/run-test.yml
@@ -57,7 +57,7 @@ jobs:
           name: coverage-report
           path: target/site/jacoco/index.html
 
-
       - name: Check code coverage
         id: check-coverage
-        run: mvn clean verify jacoco:report
+        run: |
+          mvn clean verify jacoco:report || echo "::error line=1::Coverage checks have not been met"
